### ISSUE TITLE
Add a Sorting File

### ISSUE THREAD

**Issue by prokan468** [vipu18/Hacktober-fest-2023#5]
Hey! Can I please add a sorting script written in python. In fact, i think we can add a folder that has all DSA (sortings and searching related scripts)... this way this repo will have some hits too! Looking forward to your reply!

**Comment by vipu18** [comment]
Sure! You can add them. Just don't do it in bulk.

**Comment by himughanakash** [comment]
do we need to submit code in python only or we can use different languages like cpp, java.

**Comment by vipu18** [comment]
Yes, you have to submit your code in python. Sorry for the late reply.

**Comment by himughanakash** [comment]
Ok thanks.
